# tetris-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Valorant-deployment
spec:
  replicas: 1 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: Valorant
  template:
    metadata:
      labels:
        app: Valorant
    spec:
      containers:
        - name: Valorant
          image: dharma/Valorant # Replace with the actual image tag
          ports:
            - containerPort: 80 # Replace with the port your Tetris game listens on